print("test action")\nraise Exception("This is a test failure")
